project:
  type: website
  output-dir: docs

toc: true

execute: 
  freeze: auto

website:
  title: "Software Development for Research"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - about.qmd
      - getting-started.ipynb
      - managing-environment.ipynb
      - version-control.ipynb
      - remote-version-control.ipynb
      - classes-objects.ipynb
      - files-command-line.ipynb

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
